import { precacheAndRoute } from "workbox-precaching";

// Precache all of the assets generated by your build process.
// Their URLs are automatically provided by the workbox build process.
precacheAndRoute(self.__WB_MANIFEST);
